# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 20:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IconId', models.IntegerField(verbose_name='图片id')),
                ('IconUrl', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_activity', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '用户头像',
                'verbose_name_plural': '用户头像',
                'db_table': 'UerIcon',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user_name', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[35678]\\d{9}', '请输入正确的手机号')], verbose_name='手机号')),
                ('pet_name', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, '昵称长度最小为三')], verbose_name='昵称')),
                ('pass_word', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.DateField(auto_now_add=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('site', models.CharField(blank=True, max_length=200, null=True, verbose_name='所在地')),
                ('native_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='籍贯')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'userTable',
            },
        ),
        migrations.AddField(
            model_name='usericon',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserTable', verbose_name='用户id'),
        ),
    ]
