# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usericon',
            name='IconId',
        ),
        migrations.RemoveField(
            model_name='usericon',
            name='IconUrl',
        ),
        migrations.AddField(
            model_name='usericon',
            name='logo',
            field=models.ImageField(default='head/memtx.png', upload_to='head/%Y%m/%d', verbose_name='店铺LOGO'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('1[35678]\\d{9}', '请输入正确的手机号')], verbose_name='手机号'),
        ),
    ]
