# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190123_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='logo',
            field=models.ImageField(default='head/memtx.png', upload_to='head/%Y%m/%d', verbose_name='店铺LOGO'),
        ),
    ]
