# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 14:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190214_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=30, verbose_name='博客标题')),
                ('author', models.CharField(max_length=30, validators=['作', '者', '名', '字'])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章详细内容')),
                ('recommend_rate', models.SmallIntegerField(choices=[(5, '非常推荐'), (4, '较推荐'), (3, '推荐'), (2, '中等'), (1, '不推荐')], verbose_name='推荐指数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('like', models.IntegerField(default=0, validators=['点', '赞', '数'])),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Classify', verbose_name='分类')),
                ('label', models.ManyToManyField(to='index.Label', verbose_name='博客标签')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
    ]
