# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 01:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4, '用户名至少4位')])),
                ('pass_word', models.CharField(max_length=32)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userTable',
            },
        ),
    ]
