# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0002_addresstable2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expressage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=10, verbose_name='快递名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运费')),
            ],
            options={
                'verbose_name': '快递选择',
                'verbose_name_plural': '快递选择',
            },
        ),
    ]
