# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0005_auto_20190213_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否是推荐方式'),
        ),
    ]
